[project]
name = "funtasia-pipeline"
dynamic = ["version"]
requires-python = ">= 3.8"
description = "Tool to generate assets for Funtasia 3D map"
readme = "README.md"

dependencies = [
  "typer>=0.27",
  "colorama>=0.4.6; os_name == 'nt'",
  "httpx>=0.28",
  "quart>=0.23"
]

classifiers = [
  "Development Status :: 1 - Planning",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Build Tools",
  "Natural Language :: English",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12"
]

[project.scripts]
nipple = "pipeline.cli:app"
fuNtasIaPiPeLinE = "pipeline.cli:app"
pipeline = "pipeline.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/pipeline/__about__.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.agent",
  "/.blender",
  "/.github",
  "/.notes",
  "setup",
  "/docs",
]

[tool.hatch.build.targets.wheel]
packages = ["src/pipeline"]
