[general]
version="v0-0-0"

[blender]
exe="C:\\Program Files\\Blender Foundation\\Blender 5.0\\blender.exe" #To be replaced during setup
script="pipeline/pipelines/three_d/server/blender"
config = "config/export.json"
maxworkers=2

[sketchup]
maxworkers=6

[repos]
root="C:\\Users\\ryan_\\Documents\\School\\Non-Academic\\Funtasia" #To be replaced during setup
data = "data-funtasia"
assets = "app-funtasia/assets-funtasia"
app = "app-funtasia"
pipeline = "pipeline-funtasia"
