[general]
version="v0-06-08"

[dir]
blend="blend"
skp="skp"
backup_dir=".blend/backup"
working_dir=".blend/working"

[blender]
exe="C:\\Program Files\\Blender Foundation\\Blender 5.0\\blender.exe"
config = "config/export.json"
maxworkers=2

[sketchup]
maxworkers=6

[repos]
MAINDIR="C:\\Users\\ryan_\\Documents\\School\\Non-Academic\\Funtasia"
files = "3dfiles-funtasia"
assets = "app-funtasia/assets-funtasia"
app = "app-funtasia"
pipeline = "pipeline-funtasia"
